### PR TITLE
chore: notebook with hideable cells

### PR DESCRIPTION
**Pull request by qued**
With this PR it is no longer necessary to keep a seperate version of the notebook `pipeline-section.ipynb` for demos.

#### Background
For the purposes of demos, markdown cells with detailed explanation are distracting, and it's desirable that code output is removed so it's clear the demo is "live". For these reasons we kept the notebook `pipeline-section.ipynb` as an example notebook, and a notebook derived from `pipeline-section.ipynb` for demos only.

This PR adds a javascript cell to the top of the notebook the output of which has a link that toggles the visibility of all cells with explanatory markdown. The javascript code also hides the input portion of its own cell since it is not relevant to the demo.

#### Explanation
The way this works is that the explanatory markdown cells have Jupyter tags. Cell tags can be viewed/changed via View -> Cell Toolbar -> Tags.
image

The javascript toggles the visibility of only those cells with the tag `explanatory_cell`, and hides the input of only those cells with the tag `execution_cell`.

HTML and javascript is active in a notebook when it is in the output of a cell. This notebook has been pre-executed so that the javascript is in the output of the first cell so it should execute as soon as the notebook loads -- however, Jupyter guards against this to prevent a notebook received from elsewhere from executing malicious code without any action from the notebook user. So on first loading the notebook the javascript in the output of the first cell is stripped automatically because the output is not *trusted*. The output of the script cell can be designated as trusted by either executing it locally, or going File -> Trust Notebook.
image

This trust persists as long as any changes to the output are performed and recorded by the local Jupyter server. For more details see the [Jupyter security docs](https://jupyter-notebook.readthedocs.io/en/stable/security.html#the-problem).

#### Preparing the notebook for a demo
Once the output is trusted, the link appears in the output and can be clicked to hide explanatory markdown cells. Doing this in addition to Cell -> All Output -> Clear prepares the notebook for a demo.

Incidentally, clearing all cell output also clears the output of the script cell, erasing the link that allows you to toggle the visibility of the explanatory cells. It might be desirable for the link to be hidden for demos, but it can be made visible again by executing it again. Even though it is hidden, it can be selected by moving to the top of the notebook.
image

(Sneaky hidden cell)

#### Testing
- Open the notebook `pipeline-section.ipynb`.
- Trust the notebook - the code for the first cell should disappear and the link should appear.
- Click the link and ensure explanatory markdown cells disappear (might have to click twice, I think this is a focus issue).
- Click the link again and ensure explanatory markdown cells reappear.
- Close and shutdown the notebook.
- Open the notebook again - code for the first cell should still be hidden and link should be visible.
- Run `make test-integration` to ensure notebook functionality is unchanged.

### CODE REVIEW

**Review by MthwRobinson — APPROVED** [review]
Hooray for toggles!

**Comment by cragwolfe** [comment]
> Once the output is trusted, the link appears in the output and can be clicked to hide explanatory markdown cells. Doing this in addition to Cell -> All Output -> Clear prepares the notebook for a demo.

Probably worth including this critical hint the first cell as well.

**Review by cragwolfe — CHANGES_REQUESTED** [review]
see other comment

**Comment by cragwolfe** [comment]
Actually one more request: please update `nbdev_clean --fname pipeline-notebooks/pipeline-section.ipynb`. Some point soon we should add a CI test to make sure `nbdev_clean` on all notebooks does not result in a git diff.

**Comment by qued** [comment]
@cragwolfe On the `nbdev_clean`, by default it's going to clean out the metadata from the cells, which is where the tags are (hence breaking the toggle functionality). I'll look for some way around that.

**Comment by qued** [comment]
@cragwolfe Added a hint and cleaned out metadata other than tags in [ad724c0](https://github.com/Unstructured-IO/pipeline-sec-filings/pull/2/commits/ad724c08b9e4ed272fb29228d02a4402e687ec0d). It looks like there are ways to whitelist metadata keys with nbdev so we should be able to use tags and clean notebooks with nbdev in CI.

**Review by cragwolfe — APPROVED** [review]
LGTM

**Pull request merged**
