### PR TITLE
feat: add logging config

### PR DESCRIPTION
**Pull request by natygyoon**
Adds a proper `logger_config.yaml` for uvicorn.

**Test Instructions** 

`make run-web-app` should include formatting output specific to `logger_config.yaml` as shown below.

```
(unstructured) ygyoon@Nathans-MacBook-Pro pipeline-sec-filings % make run-web-app
PYTHONPATH=. uvicorn prepline_sec_filings.api.app:app --log-config logger_config.yaml --reload
2023-03-31 18:10:01,690 uvicorn.error INFO Will watch for changes in these directories: ['/Users/ygyoon/pipeline-sec-filings']
2023-03-31 18:10:01,690 uvicorn.error INFO Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
2023-03-31 18:10:01,690 uvicorn.error INFO Started reloader process [99317] using WatchFiles
2023-03-31 18:10:03,161 uvicorn.error INFO Started server process [99328]
2023-03-31 18:10:03,161 uvicorn.error INFO Waiting for application startup.
2023-03-31 18:10:03,161 uvicorn.error INFO Application startup complete.
```
Test hitting the API with:
```
curl -X 'POST' \
  'http://localhost:8000/sec-filings/v0.2.1/section' \
  -H 'accept: application/json' \
  -H 'Content-Type: multipart/form-data' \
  -F 'text_files=@sample-docs/rgld-10-K-85535-000155837021011343.xbrl' \
  -F section=RISK_FACTORS | jq -C
```
And note the output lines from the `pipeline-sec-filings` logger:

```
...
2023-03-31 18:10:29,766 unstructured INFO Reading document from string ...
2023-03-31 18:10:29,817 unstructured INFO Reading document ...
2023-03-31 18:10:30,903 127.0.0.1:59685 POST /sec-filings/v0.2.1/section HTTP/1.1 - 200 OK
...
```

### CODE REVIEW

**Review by qued — CHANGES_REQUESTED** [review]
Here's what I see when running the suggested test:
```shell
PYTHONPATH=. uvicorn prepline_sec_filings.api.app:app --log-config logger_config.yaml --reload
2023-03-31 18:14:25,668 uvicorn.error INFO Will watch for changes in these directories: ['/Users/alanbertl/projects/forks/pipeline-sec-filings']
2023-03-31 18:14:25,668 uvicorn.error INFO Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
2023-03-31 18:14:25,668 uvicorn.error INFO Started reloader process [3136] using WatchFiles
2023-03-31 18:14:26,563 uvicorn.error INFO Started server process [3160]
2023-03-31 18:14:26,563 uvicorn.error INFO Waiting for application startup.
2023-03-31 18:14:26,563 uvicorn.error INFO Application startup complete.
2023-03-31 18:14:34,786 127.0.0.1:64530 POST /sec-filings/v0.2.1/section HTTP/1.1 - 200 OK
```
So no `unstructured` messages in the log.

**Comment by natygyoon** [comment]
Could you try with the new command? I should have made it clearer to run the curl command from `sample-docs` folder. Let me know if `unstructured` info messages are still not showing up. Thanks!

**Comment by cragwolfe** [comment]
logging statements from within the unstructured library would, though. and the level can be updated in the config, of course. although, it would be good to verify that.

**Comment by qued** [comment]
@cragwolfe Ah yep, I see it in `unstructured` 0.2.5. Still, I don't see that log output when the web app is running. I just checked with an install into a fresh environment.

**Comment by cragwolfe** [comment]
@qued , given that this config is identical to https://github.com/Unstructured-IO/unstructured-api/pull/64 and known to work with modern versions of unstructured (set the level to DEBUG), i think this PR is complete. E.g.:

```
uvicorn prepline_general.api.app:app --reload --log-config logger_config.yaml
2023-04-07 13:34:58,454 uvicorn.error INFO Will watch for changes in these directories: ['/Users/cragwolfe/r/unstructured-api']
2023-04-07 13:34:58,454 uvicorn.error INFO Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
2023-04-07 13:34:58,454 uvicorn.error INFO Started reloader process [28450] using WatchFiles
2023-04-07 13:35:00,615 uvicorn.error INFO Started server process [28461]
2023-04-07 13:35:00,616 uvicorn.error INFO Waiting for application startup.
2023-04-07 13:35:00,616 uvicorn.error INFO Application startup complete.
2023-04-07 13:35:01,077 unstructured DEBUG Not narrative. Text does not contain a verb:

Lorem ipsum dolor sit amet.

```

**Pull request merged**
